version: '2.1'
orbs:
  codecov: codecov/codecov@3.2.2
jobs:
  build:
    working_directory: ~/nodejs_express_clean_architecture
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm run test:unit:coverage
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/clover.xml
