version: '2.1'
orbs:
  codecov: codecov/codecov@3.2.2
jobs:
  build:
    working_directory: ~/nodejs_express_clean_architecture
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: npm run test:unit:coverage
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/clover.xml
